name: Build and Deploy

on:
  push:
    branches: 
      - main
      - stage

env:
  AWS_REGION: us-east-1
  S3BUCKET: laravel.douglasramiro.com.br#


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::261709225091:role/github-actions-role
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Environment Variables
        id: setVars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "DB_USERNAME=$(aws ssm get-parameter --name /database/prd/username --with-decryption --query Parameter.Value)" >> $GITHUB_OUTPUT
          fi
          if [[ "${{github.base_ref}}" == "stage" || "${{github.ref}}" == "refs/heads/stage" ]]; then
            echo "DB_USERNAME=$(aws ssm get-parameter --name /database/stage/username --with-decryption --query Parameter.Value)" >> $GITHUB_OUTPUT
          fi

      - name: Replace database username
        run: echo ${{steps.setVars.outputs.DB_USERNAME}}


