name: Build and Deploy

on:
  push

env:
  AWS_REGION: us-east-1
  S3BUCKET: laravel.douglasramiro.com.br#


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::261709225091:role/github-actions-role
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: STS
        run: aws sts get-caller-identity

      - name: Recover database username
        run: echo "::set-output name=DB_USERNAME::$(aws ssm get-parameter --name /database/username --with-decryption --query Parameter.Value)"
        id: recover-database-username

      - name: Replace database username
        run: echo ${{steps.recover-database-username.outputs.DB_USERNAME}}


