name: Build and Deploy

on:
  push:
    branches: 
      - main
      - stage

env:
  AWS_REGION: us-east-1
  S3BUCKET: laravel.douglasramiro.com.br#


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::261709225091:role/github-actions-role
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Environment Variables
        id: setVars
        run: |
          if [[ "${{github.base_ref}}" == "main" || "${{github.ref}}" == "refs/heads/main" ]]; then
            echo "DB_USERNAME=$(aws ssm get-parameter --name /database/prd/username --with-decryption --query Parameter.Value)" >> $GITHUB_OUTPUT
          fi
          if [[ "${{github.base_ref}}" == "stage" || "${{github.ref}}" == "refs/heads/stage" ]]; then
            echo "DB_USERNAME=$(aws ssm get-parameter --name /database/stage/username --with-decryption --query Parameter.Value)" >> $GITHUB_OUTPUT
          fi

      - name: "Add mask to sensitive info"
        run: |
          echo "::add-mask::${{ steps.setVars.outputs.DB_USERNAME }}"

      - name: Create .env file
        run: cp .env.example .env

      - name: Replace database username
        uses: datamonsters/replace-action@v2
        with:
          files: '.env'
          replacements: '##DB_USERNAME##=${{steps.setVars.outputs.DB_USERNAME}}'

      - name: Validate .env
        run: cat .env

      - name: Deploy on AWS
        run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name laravel --deployment-group-name laravel-codedeploy-group --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures


